# Generated by Django 5.0.4 on 2024-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_place',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
